[package]
org = "wso2"
name = "messagestore"
version = "1.0.4-SNAPSHOT"
distribution = "2201.13.3"

[build-options]
observabilityIncluded = true

[[package.modules]]
name = "messagestore.api"
export = true
