[package]
org = "wso2"
name = "messagestore"
version = "1.0.4"
distribution = "2201.13.3"

[build-options]
observabilityIncluded = true

[[package.modules]]
name = "messagestore.api"
export = true

[[platform.java21.dependency]]
path = "/Users/pasindug/Documents/Products/fork-repos/product-integrator-websubhub/build-config/patches/ballerinax-java.jms/1.2.1/platform/java21/activemq-all-5.18.6.jar"
artifactId = "activemq-all"
version = "5.18.6"
groupId = "org.apache.activemq"

[[platform.java21.dependency]]
path = "/Users/pasindug/Documents/Products/fork-repos/product-integrator-websubhub/build-config/patches/ballerinax-java.jms/1.2.1/platform/java21/log4j-api-2.20.0.jar"
artifactId = "log4j-api"
version = "2.20.0"
groupId = "org.apache.logging.log4j"

[[platform.java21.dependency]]
path = "/Users/pasindug/Documents/Products/fork-repos/product-integrator-websubhub/build-config/patches/ballerinax-java.jms/1.2.1/platform/java21/log4j-core-2.20.0.jar"
artifactId = "log4j-core"
version = "2.20.0"
groupId = "org.apache.logging.log4j"
